<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\KnowledgeOps.AI\KnowledgeOps.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Account\" />
    <Folder Include="Models\Copilot\" />
    <Folder Include="Models\Documents\" />
    <Folder Include="Models\Requests\" />
    <Folder Include="Views\Documents\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f26e800f-68c5-4974-bd1a-6211d136f6ad</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" /> 
  </ItemGroup>
</Project>
